language: ruby
cache: bundler

addons:
  code_climate:
    repo_token: 9915e76dfd68b6208b36d41238a429cd8b48fa534e287dbf20c8edf4b2fd5abf


rvm:
  - 2.1.1
  - 2.0.0

script: 'bundle exec rake spec'

notifications:
  email:
    recipients:
      - eturino@eturino.com
    on_failure: change
    on_success: never